### ISSUE TITLE
Error in Polybius decryption

### ISSUE THREAD

**Issue by cs-t1** [Titoutee/NSIEncryption#1]
The software spanws an exception whenever trying to decrypt a message using the
Polybius scheme, when said message is ill-formed.

## Steps to reproduce

Chose "Polybius/Decrypt" and type any none-Polybius message and then press "Compute".

**Comment by Titoutee** [comment]
This issue has already been detected and I will prolly use regex to check whether the form of the encrypted message fed in is in the correct format (being a sequence of numeric doublets)

**Comment by cs-t1** [comment]
Is it now fixed?

**Comment by Titoutee** [comment]
Sure!
